name: Deploy

on:
  push:
    branches: [develop]

jobs:
  deploy:
    name: Deploy Laravel Dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: cd ${{ secrets.PROJECT_PATH }} && git pull